import React,{useEffect,useMemo,useRef,useState} from 'react';
import {X,Clock3,LoaderCircle,ArrowDownToLine,Check,AlertCircle,Braces,ChevronRight} from 'lucide-react';
import './diagnostics.css';

type Call={id:string;kind:'jev'|'generation';stage:string;requested_model?:string|null;response_model?:string|null;started_elapsed_ms:number|null;duration_ms:number|null;finished_elapsed_ms?:number;status:string;input?:unknown;output:unknown;usage?:{prompt_tokens?:number;completion_tokens?:number;total_tokens?:number};error?:string;source?:string;action?:string;target?:string};
type RunInfo={id:string;query:string;status:string;elapsed_ms:number};
const names:Record<string,string>={decision:'Browser decision',semantic_plan:'Task planning',field_text:'Text to type',completion_check:'Stage completion check',guidance:'Stall guidance',result_summary:'Final summary',result_extraction:'Result extraction',generation:'Generation'};
const phases:Record<string,string>={running:'Running',succeeded:'Returned',failed:'Failed',interrupted:'Interrupted'};
const seconds=(ms:number|null|undefined)=>ms==null?'Not recorded':`${(Math.max(0,ms)/1000).toFixed(2)} s`;
const position=(ms:number|null)=>{if(ms==null)return 'Start not recorded';return `+${(ms/1000).toFixed(2)} s`;};
function outputText(output:unknown){if(output==null)return '';if(typeof output==='string'){try{return JSON.stringify(JSON.parse(output),null,2);}catch{return output;}}return JSON.stringify(output,null,2);}
function displayInput(input:unknown){if(input&&typeof input==='object'&&!Array.isArray(input)){const {model,...content}=input as Record<string,unknown>;return content;}return input;}

export default function Diagnostics({run,elapsedMs,api,onClose}:{run:RunInfo|null;elapsedMs:number;api:(path:string,options?:RequestInit)=>Promise<any>;onClose:()=>void}){
 const [calls,setCalls]=useState<Call[]>([]),[legacy,setLegacy]=useState(false),[loading,setLoading]=useState(!!run),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[selectedId,setSelectedId]=useState<string|null>(null),[serverElapsed,setServerElapsed]=useState(0);
 const panel=useRef<HTMLElement>(null),close=useRef<HTMLButtonElement>(null),closeAction=useRef(onClose);closeAction.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeAction.current();}if(e.key==='Tab'){const nodes=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],summary,[tabindex="0"]')??[]).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key,true);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key,true);previous?.focus();};},[]);
 useEffect(()=>{setCalls([]);setSelectedId(null);setLegacy(false);setError('');setLoading(!!run);setServerElapsed(0);if(!run)return;let stopped=false,timer:ReturnType<typeof setTimeout>,revision='';const controller=new AbortController();const poll=async()=>{try{const data=await api(`/api/runs/${run.id}/diagnostics?since=${encodeURIComponent(revision)}`,{signal:controller.signal});if(stopped)return;revision=data.revision;setServerElapsed(data.elapsed_ms??0);if(data.calls){setCalls(data.calls);setLegacy(!!data.legacy);}setError('');setLoading(false);if(!['completed','partial','summarized','failed','cancelled'].includes(data.run_status))timer=setTimeout(poll,900);}catch{if(!stopped){setLoading(false);setError('The log could not be read; retrying.');timer=setTimeout(poll,2200);}}};poll();return()=>{stopped=true;controller.abort();clearTimeout(timer);};},[run?.id]);
 const taskMs=Math.max(elapsedMs,serverElapsed,run?.elapsed_ms??0);
 const shown=useMemo(()=>calls.filter(c=>filter==='all'||c.kind===filter),[calls,filter]);
 const selected=shown.find(c=>c.id===selectedId)??shown.at(-1);
 const duration=(c:Call)=>c.status==='running'&&c.started_elapsed_ms!=null?Math.max(0,taskMs-c.started_elapsed_ms):c.duration_ms;
 const finished=calls.filter(c=>c.duration_ms!=null);
 const longest=finished.reduce<Call|undefined>((best,c)=>!best||(c.duration_ms??0)>(best.duration_ms??0)?c:best,undefined);
 const maxDuration=Math.max(1,...calls.map(c=>duration(c)??0));
 const stats=(kind:string)=>{const group=finished.filter(c=>c.kind===kind);return {count:calls.filter(c=>c.kind===kind).length,ms:group.reduce((sum,c)=>sum+(c.duration_ms??0),0),average:group.length?group.reduce((sum,c)=>sum+(c.duration_ms??0),0)/group.length:null};};
 const jev=stats('jev'),generation=stats('generation');
 function download(){const body=JSON.stringify({query:run?.query,elapsed_ms:taskMs,legacy,calls:calls.map(({requested_model,response_model,input,...call})=>({...call,input:displayInput(input)}))},null,2);const url=URL.createObjectURL(new Blob([body],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='webjev-model-calls.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="diagnostics-shade" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}>
  <section className="diagnostics-panel" role="dialog" aria-modal="true" aria-labelledby="diagnostics-title" ref={panel}>
   <header className="diagnostics-heading"><div><span className="diagnostics-kicker">Model calls</span><h2 id="diagnostics-title">Calls and latency</h2></div><div className="diagnostics-tools">{calls.length>0&&<button className="quiet-button" onClick={download}><ArrowDownToLine size={15}/>Export log</button>}<button className="icon-button" aria-label="Close the model-call panel" ref={close} onClick={onClose}><X size={21}/></button></div></header>
   {!run?<div className="diagnostics-empty"><Braces size={32}/><h3>Start a task to see its model calls</h3><p>Each call's input, output and latency appear here live.</p></div>:<>
    <p className="diagnostics-query">{run.query}</p>
    <div className="diagnostics-stats"><div><span>Task time</span><strong>{seconds(taskMs)}</strong><small>{calls.length} model calls</small></div><div className="metric-jev"><span>Decision model, total</span><strong>{seconds(jev.ms)}</strong><small>{jev.count} calls · mean {seconds(jev.average)}</small></div><div className="metric-generation"><span>Text LLM, total</span><strong>{seconds(generation.ms)}</strong><small>{generation.count} calls · mean {seconds(generation.average)}</small></div></div>
    <div className="diagnostics-insight">{longest?<button onClick={()=>{setFilter('all');setSelectedId(longest.id);}}><Clock3 size={14}/><span>Slowest: {names[longest.stage]??longest.stage}</span><strong>{seconds(longest.duration_ms)}</strong><ChevronRight size={14}/></button>:<span>Latency comparison appears once calls finish</span>}<small>Timed per finished logical call, including retries and network wait; a hedged duplicate request is not counted twice.</small></div>
    {legacy&&<p className="diagnostics-notice">Older runs show saved records only. Inputs, outputs and durations that were not recorded are not guessed.</p>}
    {error&&<p className="diagnostics-error" role="alert">{error}</p>}
    <div className="diagnostics-filters" aria-label="Filter model calls">{[['all','All'],['jev','Decision model'],['generation','Text LLM']].map(([value,label])=><button key={value} className={filter===value?'selected':''} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}<span>{value==='all'?calls.length:calls.filter(c=>c.kind===value).length}</span></button>)}<span className="diagnostics-live">{calls.some(c=>c.status==='running')&&<><span className="pulse-dot"/>Live</>}</span></div>
    {loading?<div className="diagnostics-empty"><LoaderCircle className="spin" size={23}/><p>Reading the call log</p></div>:shown.length===0?<div className="diagnostics-empty"><Braces size={27}/><p>{calls.length?'No calls of this kind yet':'No model calls yet'}</p></div>:<div className="diagnostics-body">
     <div className="diagnostics-list" aria-label="Model calls">{shown.map(c=><button key={c.id} className={`diagnostics-call ${selected?.id===c.id?'selected':''}`} onClick={()=>setSelectedId(c.id)} aria-pressed={selected?.id===c.id}><div className="call-meta"><span className={`call-kind kind-${c.kind}`}>{c.kind==='jev'?'Decision':'Text LLM'}</span><time>{position(c.started_elapsed_ms)}</time></div><div className="call-title"><strong>{names[c.stage]??c.stage}</strong><span>{seconds(duration(c))}</span></div><p>{c.action?[c.action,c.target].filter(Boolean).join(' · '):c.kind==='jev'?'Browser action decision':'Text generation'}</p><div className="call-duration-track"><span className={`kind-${c.kind}`} style={{width:`${Math.max(2,(duration(c)??0)/maxDuration*100)}%`}}/></div><span className={`call-status status-${c.status}`}>{c.status==='running'?<LoaderCircle size={11} className="spin"/>:c.status==='succeeded'?<Check size={11}/>:<AlertCircle size={11}/>} {phases[c.status]??c.status}</span></button>)}</div>
     {selected&&<div className="diagnostics-detail"><div className="diagnostics-detail-heading"><span className={`call-kind kind-${selected.kind}`}>{selected.kind==='jev'?'Decision':'Text LLM'}</span><strong>{names[selected.stage]??selected.stage}</strong><span>{seconds(duration(selected))}</span></div><dl className="diagnostics-properties"><div><dt>Started</dt><dd>{position(selected.started_elapsed_ms)}</dd></div><div><dt>Status</dt><dd>{phases[selected.status]??selected.status}</dd></div>{selected.usage?.total_tokens!=null&&<div><dt>Tokens</dt><dd>{selected.usage.total_tokens.toLocaleString()}<span> input {selected.usage.prompt_tokens??'—'} / output {selected.usage.completion_tokens??'—'}</span></dd></div>}</dl><div className="diagnostics-output-title"><h3>Input</h3></div>{selected.input!=null?<pre className="diagnostics-output diagnostics-input" tabIndex={0}>{outputText(displayInput(selected.input))}</pre>:<div className="diagnostics-output-empty diagnostics-input-empty">No input was saved for this call.</div>}<div className="diagnostics-output-title"><h3>Output</h3>{selected.source==='saved_stage'&&<span>Saved stage result</span>}</div>{selected.error&&<p className="diagnostics-error">{selected.error}</p>}{selected.output!=null?<pre className="diagnostics-output" tabIndex={0}>{outputText(selected.output)}</pre>:<div className="diagnostics-output-empty">{selected.status==='running'?<><LoaderCircle size={18} className="spin"/>Waiting for the model…</>:selected.status==='failed'?'This call returned no output to show.':'No output was saved for this call.'}</div>}</div>}
    </div>}
   </>}
  </section>
 </div>;
}
