import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUp,ArrowUpRight,ArrowRight,Check,ChevronDown,Clock3,ExternalLink,Globe2,MousePointer2,Plus,Square,Laptop,TrainFront,FileText,Calculator,Stethoscope,Landmark,LoaderCircle,AlertCircle,Copy,Download,RotateCcw,X} from 'lucide-react';
import './styles.css';
import Diagnostics from './Diagnostics';

type Preset={id:string;label:string;query:string;target_website:string};
type DecisionModel={id:string;label:string;available:boolean;description?:string};
type Step={step:number;action:string;label:string;url?:string;elapsed_ms:number;status:string;value?:string};
type Frame={url:string;width:number;height:number;elapsed_ms:number};
type Cell={value:string|null;observation_id?:number;quote?:string};
type Result={status:string;mode?:string;summary:string;columns:{key:string;label:string}[];rows:{cells:Record<string,Cell>}[];missing_fields?:string[];notes?:string[];checks?:{name?:string;label?:string;passed:boolean}[]};
type Run={id:string;query:string;client_request_id?:string;decision_model?:string;browser_backend?:string;status:string;phase?:string;message?:string;created_at:string;elapsed_ms:number;steps:Step[];frame?:Frame;browser?:{url:string;title:string;viewer_url?:string};result?:Result;pointer?:{x:number;y:number;width:number;height:number};last_event_id:number};
type Event={id:number;type:string;data:any};
const terminal=new Set(['completed','partial','summarized','failed','cancelled']);
const labels:Record<string,string>={queued:'Getting ready',connecting:'Opening the browser',running:'Working',extracting:'Summarizing the result',needs_login:'Waiting for you to sign in',completed:'Run finished',partial:'Run finished',summarized:'Result ready',failed:'Run finished',cancelled:'Stopped'};
const presetIcons:Record<string,typeof Globe2>={'apple-macbook-air':Laptop,'mta-brooklyn-maps':TrainFront,'arxiv-paper-venue':FileText,'wolfram-hilbert':Calculator,'mayo-infertility':Stethoscope,'govuk-visa':Landmark};
const timing=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000));return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`};
async function api(path:string,options:RequestInit={}){
 let r:Response,data:any;
 try{r=await fetch(path,{credentials:'same-origin',...options,signal:options.signal??AbortSignal.timeout(12000),headers:{'Content-Type':'application/json',...options.headers}});data=await r.json();}
 catch{throw new Error('The connection was interrupted. Please try again.');}
 if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'That did not work. Please try again.');return data;
}
const post=(path:string,body?:unknown)=>api(path,{method:'POST',body:JSON.stringify(body??{})});
const safeUrl=(value?:string)=>{try{const u=new URL(value??'');return ['https:','http:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}};
type Pending={query:string;nonce:string;created_at:string};
function requestId(){
 // getRandomValues also works on HTTP LAN origins; randomUUID requires HTTPS.
 const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;
 const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
 return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;
}
function storage(key:string,value?:string|null){try{if(value===undefined)return sessionStorage.getItem(key);if(value===null)sessionStorage.removeItem(key);else sessionStorage.setItem(key,value);}catch{}return null;}
function savedPending():Pending|null{try{const p=JSON.parse(storage('browser-agent-pending')??'null');return p&&typeof p.query==='string'&&typeof p.nonce==='string'?p:null;}catch{return null;}}
function matchesPending(candidate:Run|null,pending:Pending){if(!candidate||candidate.query!==pending.query)return false;if(candidate.client_request_id)return candidate.client_request_id===pending.nonce;return !pending.created_at||Date.parse(candidate.created_at)>=Date.parse(pending.created_at)-5000;}

function useReceivedFrame(runId:string|undefined,incoming:Frame|undefined){
 const [displayed,setDisplayed]=useState<(Frame&{src:string})|null>(null),[frameError,setFrameError]=useState(false);
 const transfer=useRef({generation:0,busy:false,pending:null as Frame|null,lastUrl:'',controller:null as AbortController|null,url:null as string|null,retry:null as ReturnType<typeof setTimeout>|null,failures:0});
 const pump=useRef<()=>void>(()=>{});
 pump.current=()=>{const t=transfer.current;if(t.busy||!t.pending)return;const generation=t.generation;const frame=t.pending;t.pending=null;t.busy=true;t.lastUrl=frame.url;const controller=new AbortController();t.controller=controller;const timeout=setTimeout(()=>controller.abort(),15000);
  void(async()=>{try{const response=await fetch(frame.url,{credentials:'same-origin',signal:controller.signal});if(!response.ok)throw new Error('frame');const blob=await response.blob();if(generation!==t.generation)return;const src=URL.createObjectURL(blob);const decoded=new Image();decoded.src=src;try{await decoded.decode();}catch{URL.revokeObjectURL(src);throw new Error('image');}if(generation!==t.generation){URL.revokeObjectURL(src);return;}const old=t.url;t.url=src;t.failures=0;setFrameError(false);setDisplayed({...frame,src});if(old)requestAnimationFrame(()=>URL.revokeObjectURL(old));}
   catch{if(generation===t.generation){setFrameError(true);t.failures+=1;if(!t.pending&&t.failures<3)t.pending=frame;}}
   finally{clearTimeout(timeout);if(generation===t.generation){t.busy=false;t.controller=null;if(t.pending)t.retry=setTimeout(()=>pump.current(),t.failures?900:0);}}
  })();
 };
 useEffect(()=>{const t=transfer.current;t.generation+=1;t.controller?.abort();if(t.retry)clearTimeout(t.retry);if(t.url)URL.revokeObjectURL(t.url);t.url=null;t.pending=null;t.lastUrl='';t.busy=false;t.failures=0;setDisplayed(null);setFrameError(false);return()=>{t.generation+=1;t.controller?.abort();if(t.retry)clearTimeout(t.retry);if(t.url)URL.revokeObjectURL(t.url);t.url=null;t.pending=null;t.busy=false;};},[runId]);
 useEffect(()=>{const t=transfer.current;if(incoming&&incoming.url!==t.lastUrl){t.pending=incoming;pump.current();}},[runId,incoming?.url]);
 return {displayed,frameError};
}

function App(){
 const [presets,setPresets]=useState<Preset[]>([]),[query,setQuery]=useState(''),[run,setRun]=useState<Run|null>(null),[sending,setSending]=useState(false),[error,setError]=useState(''),[offline,setOffline]=useState(false),[clock,setClock]=useState(0),[evidence,setEvidence]=useState<{cell:Cell;label:string}|null>(null),[copied,setCopied]=useState(false),[showProcess,setShowProcess]=useState(true),[diagnosticsOpen,setDiagnosticsOpen]=useState(false);
 const input=useRef<HTMLTextAreaElement>(null),log=useRef<HTMLDivElement>(null),resultArea=useRef<HTMLElement>(null),remoteInput=useRef<HTMLTextAreaElement>(null),image=useRef<HTMLImageElement>(null),runRef=useRef<Run|null>(null),seq=useRef(0),inputQueue=useRef(Promise.resolve()),elapsedAnchor=useRef({ms:0,at:performance.now()}),composing=useRef(false);
 const [connectionAttempt,setConnectionAttempt]=useState(0),[reconnectStopped,setReconnectStopped]=useState(false);
 const [models,setModels]=useState<DecisionModel[]>([]),[decision,setDecision]=useState(''),[browserInfo,setBrowserInfo]=useState<{id:string;label:string}|null>(null);
 const continueButton=useRef<HTMLButtonElement>(null),evidenceReturn=useRef<HTMLButtonElement|null>(null);
 const pendingRequest=useRef<Pending|null>(savedPending());
 const {displayed:displayedFrame,frameError}=useReceivedFrame(run?.id,run?.frame);
 runRef.current=run;
 const active=!!run&&!terminal.has(run.status),finished=!!run&&terminal.has(run.status),needsLogin=run?.status==='needs_login';
 const runModel=run?.decision_model?(models.find(m=>m.id===run.decision_model)?.label??run.decision_model):'';
 const accept=(next:Run)=>{next.steps??=[];if(next.decision_model)setDecision(next.decision_model);seq.current=next.last_event_id??seq.current;elapsedAnchor.current={ms:next.elapsed_ms??0,at:performance.now()};setRun(next);setQuery(next.query);};
 useEffect(()=>{let mounted=true;api('/api/presets').then(d=>{if(mounted)setPresets(d.presets)}).catch(e=>{if(mounted)setError(e.message)});api('/api/config').then(d=>{if(!mounted)return;setModels(d.decision_models??[]);setDecision(current=>current||d.default_decision_model||'');setBrowserInfo(d.browser??null);}).catch(()=>{});const id=storage('browser-agent-run');const pending=pendingRequest.current;if(id)api(`/api/runs/${id}`).then(d=>{if(mounted)accept(d)}).catch(e=>{if(mounted)setError(e.message)});else if(pending){setQuery(pending.query);api(`/api/runs/latest?client_request_id=${encodeURIComponent(pending.nonce)}`).then(d=>{if(!mounted)return;const candidate=('run'in d?d.run:d) as Run|null;if(matchesPending(candidate,pending)){accept(candidate!);storage('browser-agent-run',candidate!.id);storage('browser-agent-pending',null);pendingRequest.current=null;}}).catch(e=>{if(mounted)setError(e.message)});}return()=>{mounted=false};},[]);
 useEffect(()=>{if(!run?.id||terminal.has(run.status))return;let cancelled=false,failures=0,timer:ReturnType<typeof setTimeout>;const id=run.id;setReconnectStopped(false);
  const poll=async()=>{try{const d=await api(`/api/runs/${id}/updates?after=${seq.current}`);if(cancelled)return;failures=0;setOffline(false);seq.current=d.last_event_id;
    if(d.snapshot){accept(d.snapshot);}else if(d.events.length){setRun(previous=>{if(!previous||previous.id!==id)return previous;let next={...previous,steps:[...previous.steps],last_event_id:d.last_event_id};for(const e of d.events as Event[]){const data=e.data;switch(e.type){case 'phase':next.status=data.phase;next.message=data.message;break;case 'frame':next.frame=data;break;case 'browser':next.browser=data;break;case 'pointer':next.pointer=data;break;case 'result':next.result=data;break;case 'step':{const i=next.steps.findIndex(s=>s.step===data.step);if(i>=0)next.steps[i]=data;else next.steps.push(data);next.steps.sort((a,b)=>a.step-b.step);break;}}
      if(data.elapsed_ms!=null)next.elapsed_ms=Math.max(next.elapsed_ms??0,data.elapsed_ms);}
      elapsedAnchor.current={ms:next.elapsed_ms,at:performance.now()};return next;});}
    if(!terminal.has(d.status))timer=setTimeout(poll,350);
   }catch{if(!cancelled){setOffline(true);failures+=1;if(failures<5)timer=setTimeout(poll,1800);else{setReconnectStopped(true);setError('Connection lost. Pages and steps received so far are kept; reconnect to continue.');}}}};poll();return()=>{cancelled=true;clearTimeout(timer);};
 },[run?.id,finished,connectionAttempt]);
 useEffect(()=>{if(!active||offline){setClock(run?.elapsed_ms??0);return;}const update=()=>setClock(elapsedAnchor.current.ms+performance.now()-elapsedAnchor.current.at);update();const t=setInterval(update,250);return()=>clearInterval(t);},[active,offline,run?.id,run?.elapsed_ms]);
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[run?.steps.length,run?.steps.at(-1)?.status]);
 useEffect(()=>{if(run?.result){setTimeout(()=>resultArea.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'}),100);}},[!!run?.result]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'&&evidence)closeEvidence()};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[evidence]);
 function closeEvidence(){setEvidence(null);requestAnimationFrame(()=>evidenceReturn.current?.focus());}
 async function start(text:string,preset?:Preset){if(sending||active||text.trim().length<5)return;setSending(true);setError('');setEvidence(null);setShowProcess(true);const task=text.trim();const pending=pendingRequest.current?.query===task?pendingRequest.current:{query:task,nonce:requestId(),created_at:new Date().toISOString()};pendingRequest.current=pending;storage('browser-agent-pending',JSON.stringify(pending));try{const d=await post('/api/runs',{query:task,preset_id:preset?.id,target_website:preset?.target_website,decision_model:decision||undefined,client_request_id:pending.nonce});seq.current=0;accept(d);storage('browser-agent-run',d.id);storage('browser-agent-pending',null);pendingRequest.current=null;}catch(e){setError((e as Error).message);}finally{setSending(false);}}
 async function cancel(){if(!run)return;try{accept(await post(`/api/runs/${run.id}/cancel`));}catch(e){setError((e as Error).message)}}
 async function resume(){if(!run)return;try{await inputQueue.current;accept(await post(`/api/runs/${run.id}/resume`));remoteInput.current?.blur();}catch(e){setError((e as Error).message)}}
 function fresh(){if(active){window.open('/', '_blank', 'noopener');return;}setRun(null);setQuery('');setError('');setEvidence(null);seq.current=0;storage('browser-agent-run',null);window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>input.current?.focus(),30);}
 function remote(body:Record<string,unknown>){const id=run?.id;if(!needsLogin||!id)return;inputQueue.current=inputQueue.current.then(async()=>{await post(`/api/runs/${id}/input`,body);}).catch(e=>setError(e.message));}
 function point(e:{clientX:number;clientY:number}){const rect=image.current!.getBoundingClientRect();const width=displayedFrame?.width??1600,height=displayedFrame?.height??780;return{x:Math.max(0,Math.min(width-1,(e.clientX-rect.left)/rect.width*width)),y:Math.max(0,Math.min(height-1,(e.clientY-rect.top)/rect.height*height))};}
 function key(e:React.KeyboardEvent){if(composing.current)return;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();remoteInput.current?.blur();continueButton.current?.focus();return;}if(e.key==='a'&&(e.ctrlKey||e.metaKey)){e.preventDefault();remote({type:'key',key:'a',modifiers:2});return;}if(['Enter','Tab','Backspace','Delete','ArrowLeft','ArrowUp','ArrowRight','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();remote({type:'key',key:e.key,modifiers:e.shiftKey?8:0});}}
 const textTable=()=>{const r=run?.result;if(!r)return '';const table=r.rows.length?[r.columns.map(c=>c.label).join('\t'),...r.rows.map(row=>r.columns.map(c=>row.cells[c.key]?.value??'—').join('\t'))].join('\n'):'';return [r.mode==='llm_summary'?r.summary:'',table].filter(Boolean).join('\n\n');};
 async function copy(){try{await navigator.clipboard.writeText(textTable());setCopied(true);setTimeout(()=>setCopied(false),1500);}catch{setError('The browser does not allow copying here; use Download instead.')}}
 function download(){const text=textTable();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));a.download='webjev-result.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 const IconStatus=run?.status==='failed'?AlertCircle:Clock3;
 return <div className={`app ${run?'has-run':''}`}>
  <header className="topbar"><a className="brand" href="/" onClick={e=>{e.preventDefault();fresh();}} aria-label="WebJev browser agent home"><span className="brand-mark"><Globe2 size={22}/><MousePointer2 className="brand-cursor" size={11}/></span><span>WebJev</span><span className="brand-divider"/><span className="brand-caption">Browser Agent</span></a><div className="header-actions">{browserInfo&&<span className="browser-badge" title="Browser that runs the tasks"><Globe2 size={13}/>{browserInfo.label}</span>}{run&&<button className="quiet-button" onClick={fresh}><Plus size={16}/>New task</button>}<button className="header-state" onClick={()=>setDiagnosticsOpen(true)} aria-haspopup="dialog" aria-expanded={diagnosticsOpen}><span className="ready-dot"/>Model calls<ChevronDown size={13}/></button></div></header>
  <main>
   <section className={`composer-section ${run?'compact':''}`} aria-label="Describe a web task">
    {!run&&<div className="intro"><span className="intro-mark"><MousePointer2 size={23}/></span><h1>What should the browser do?</h1><p>Describe a task on a real website. A cloud browser carries it out step by step, and the decision model picks every action.</p></div>}
    {run&&<div className="task-heading"><span>Current task</span><span className="task-site">{run.browser?.url&&new URL(safeUrl(run.browser.url)??'https://example.com').hostname}</span></div>}
    <form className={`composer ${active?'is-busy':''}`} onSubmit={e=>{e.preventDefault();start(query);}}><label className="sr-only" htmlFor="task-input">Web task</label><textarea id="task-input" ref={input} value={query} onChange={e=>setQuery(e.target.value)} disabled={active||sending} placeholder="For example: On arxiv.org, open the abstract page of the paper &quot;Attention Is All You Need&quot; and report its submission date." onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();start(query)}}} rows={run?2:3} maxLength={6000}/><div className="composer-footer"><span><Globe2 size={14}/>{run?(active?'Working on the current task':'Edit the task and run it again'):'Find, filter and compare on live websites'}</span><div className="composer-actions">{models.length>0&&<div className="model-picker" role="radiogroup" aria-label="Decision model">{models.map(m=><button type="button" key={m.id} role="radio" aria-checked={decision===m.id} className={decision===m.id?'selected':''} disabled={active||sending||!m.available} title={m.available?(m.description??m.label):'Not configured on this server'} onClick={()=>setDecision(m.id)}>{m.label}</button>)}</div>}{active?<button type="button" className="stop-button" onClick={cancel}><Square size={12}/>Stop</button>:<button type="submit" className="send-button" disabled={sending||query.trim().length<5}>{sending?<LoaderCircle size={17} className="spin"/>:<ArrowUp size={18}/>}<span>Run</span></button>}</div></div></form>
    {error&&<div className="error-line" role="alert"><AlertCircle size={16}/>{error}{offline&&<button className="quiet-button" onClick={()=>{setError('');setConnectionAttempt(n=>n+1);}}>Reconnect</button>}<button onClick={()=>setError('')} aria-label="Dismiss"><X size={14}/></button></div>}
   </section>
   {!run&&<section className="suggestions" aria-labelledby="suggestions-title"><div className="section-heading"><div><h2 id="suggestions-title">Try a benchmark task</h2><p className="section-note">Real-website tasks from our 125-task evaluation where WebJev-35B-A3B succeeded and Jev 1.13 failed.</p></div><span>Click to run <ArrowDownIcon/></span></div><div className="preset-grid">{presets.map(p=>{const Icon=presetIcons[p.id]??Globe2;return <button className="preset" key={p.id} disabled={sending} onClick={()=>start(p.query,p)}><div className="preset-head"><span className="preset-icon"><Icon size={20}/></span><span className="preset-label">{p.label}</span><ArrowUpRight size={18} className="preset-arrow"/></div><p>{p.query}</p></button>})}</div></section>}
   {run&&<section className={`workspace ${finished?'finished':''}`} aria-label="Task workspace"><div className="workspace-heading"><div className={`phase phase-${run.status}`} role="status">{active&&run.status!=='needs_login'?<LoaderCircle size={17} className="spin"/>:<IconStatus size={17}/>}<h2>{labels[run.status]??'Working'}</h2>{runModel&&<span className="model-badge">{runModel}</span>}{offline&&<span className="connection-warning">{reconnectStopped?'Connection lost':'Connection interrupted, reconnecting'}</span>}</div><div className="workspace-meta"><Clock3 size={14}/><span className="elapsed">{timing(clock)}</span>{finished&&<button className="quiet-button" onClick={()=>setShowProcess(!showProcess)}>{showProcess?'Hide steps':'Show steps'}<ChevronDown size={15} className={showProcess?'':'rotated'}/></button>}</div></div>
    {showProcess&&<div className="execution-grid"><section className="browser-panel" aria-label="Live browser view"><div className="browser-chrome"><div className="window-dots"><i/><i/><i/></div><div className="url-bar"><Globe2 size={13}/><span>{run.browser?.url??'Preparing the browser'}</span></div>{run.browser?.viewer_url&&needsLogin?<a className="icon-button" href={safeUrl(run.browser.viewer_url)} target="_blank" rel="noreferrer" aria-label="Open this browser in a new window"><ExternalLink size={15}/></a>:<span className="live-label">{active?'Live':'Page'}</span>}</div><div className={`viewport ${needsLogin?'interactive':''}`} style={{aspectRatio:`${displayedFrame?.width??run.frame?.width??1600}/${displayedFrame?.height??run.frame?.height??780}`}} onClick={e=>{if(needsLogin&&image.current){remote({type:'click',...point(e)});remoteInput.current?.focus({preventScroll:true});}}} onWheel={e=>{if(needsLogin&&image.current)remote({type:'wheel',...point(e),delta_y:Math.max(-1000,Math.min(1000,e.deltaY))});}}>
     {displayedFrame?<><img ref={image} src={displayedFrame.src} alt={run.browser?.title?`Browser: ${run.browser.title}`:'Current browser page'} draggable={false}/>{run.pointer&&!needsLogin&&active&&<MousePointer2 className="actual-pointer" size={18} fill="white" style={{left:`${run.pointer.x/run.pointer.width*100}%`,top:`${run.pointer.y/run.pointer.height*100}%`}}/>}</>:<div className="browser-wait"><span className="waiting-window"><Globe2 size={32}/></span>{active&&<LoaderCircle className="spin" size={20}/>}<strong>{run.status==='failed'?'The browser could not open':run.frame?'Receiving the page':'Opening the page'}</strong><p>{run.status==='failed'?run.message:frameError?'The live view was interrupted; retrying.':'The page appears here live once it loads.'}</p></div>}
     {frameError&&displayedFrame&&<span className="frame-transfer-note" role="status">Live view interrupted; showing the last frame</span>}{needsLogin&&<textarea ref={remoteInput} className="remote-keyboard" aria-label="Type into the browser (sign-in or verification)" autoComplete="off" autoCorrect="off" autoCapitalize="off" spellCheck={false} onKeyDown={key} onCompositionStart={()=>composing.current=true} onCompositionEnd={e=>{composing.current=false;remote({type:'text',text:e.data});e.currentTarget.value='';}} onInput={e=>{if(!composing.current&&e.currentTarget.value){remote({type:'text',text:e.currentTarget.value});e.currentTarget.value='';}}} onPaste={e=>{e.preventDefault();remote({type:'text',text:e.clipboardData.getData('text')});}}/>}
    </div>{needsLogin&&<div className="login-bar"><div><strong>Finish signing in or the verification on the page</strong><span>{(run.browser_backend??browserInfo?.id)==='local'?'Use the page here or your Chrome window, then come back and continue.':'Or open the full browser below, sign in, then come back and continue.'}</span>{safeUrl(run.browser?.viewer_url)&&<a className="login-browser-link" href={safeUrl(run.browser?.viewer_url)} target="_blank" rel="noreferrer">Open the browser<ExternalLink size={14}/></a>}</div><button ref={continueButton} className="primary-button" onClick={resume}>Done, continue<ArrowRight size={15}/></button></div>}{run.status==='extracting'&&<div className="extracting-bar"><LoaderCircle size={16} className="spin"/><span>Summarizing what the browser found.</span></div>}</section>
    <aside className="activity-panel"><div className="activity-header"><h3>Steps</h3><span>{run.steps.length>0?`${run.steps.length} ${run.steps.length===1?'step':'steps'}`:'Not started'}</span></div><div className="activity-log" ref={log}>{run.steps.length===0?<div className="activity-empty"><span className="small-orbit"/><p>{run.message??'Preparing a dedicated browser session'}</p></div>:run.steps.map((s,i)=><div className={`step ${s.status==='running'?'current':''}`} key={s.step}><span className="step-marker">{s.status==='completed'?<Check size={11}/>:<span/>}</span><div className="step-copy"><div className="step-meta"><span>Step {i+1}</span><time>{timing(s.elapsed_ms)}</time></div><p>{s.label}</p>{s.value&&s.action==='fill'&&<span className="step-value">{s.value}</span>}</div></div>)}{active&&!offline&&run.steps.length>0&&<div className="activity-now"><span className="pulse-dot"/><span>{run.status==='extracting'?'Summarizing':needsLogin?'Waiting for sign-in':'Observing the page'}</span></div>}</div><div className="activity-footer"><span className={`small-status ${active?'active':''}`}/>{offline?(reconnectStopped?'Connection lost; last record kept':'Reconnecting'):run.status==='needs_login'?'Paused for you':active?'Actions appear here as they run':'This run has finished'}</div></aside></div>}
    {run.result&&<section className="result-panel" ref={resultArea} aria-labelledby="result-title">
     <div className="result-top"><div><h2 id="result-title">Result</h2></div>
      {(run.result.rows.length>0||run.result.mode==='llm_summary')&&<div className="result-actions"><button className="quiet-button" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>}<span>{copied?'Copied':'Copy'}</span></button><button className="quiet-button" onClick={download}><Download size={15}/><span>Download</span></button></div>}
     </div>
     {(run.result.mode==='llm_summary'||run.result.status==='failed')&&run.result.summary&&<p className="result-summary">{run.result.summary}</p>}
     {run.result.rows.length>0&&<div className="table-wrap"><table><thead><tr>{run.result.columns.map(c=><th scope="col" key={c.key}>{c.label}</th>)}</tr></thead><tbody>{run.result.rows.map((row,i)=><tr key={i}>{run.result!.columns.map(c=>{const cell=row.cells[c.key];return <td key={c.key}>{cell?.value!=null?<span>{cell.value}</span>:<span className="missing-value">—</span>}</td>})}</tr>)}</tbody></table></div>}
     <div className="result-bottom"><span/>{run.result.status==='failed'&&<button className="quiet-button" onClick={()=>start(run.query,presets.find(p=>p.query===run.query))}><RotateCcw size={14}/>Run again</button>}</div>
    </section>}
    {finished&&!run.result&&<div className="failure-panel"><AlertCircle size={22}/><div><h3>{labels[run.status]}</h3><p>{run.message??'The run stopped. Pages and steps received so far are kept above.'}</p></div><button className="quiet-button" onClick={()=>start(run.query,presets.find(p=>p.query===run.query))}><RotateCcw size={15}/>Run again</button></div>}
   </section>}
  </main><footer className="app-footer"><span>WebJev · Lexmount</span></footer>
  {diagnosticsOpen&&<Diagnostics run={run} elapsedMs={clock} api={api} onClose={()=>setDiagnosticsOpen(false)}/>}
  {evidence&&<div className="modal-shade" onClick={closeEvidence}><section className="evidence-modal" role="dialog" aria-modal="true" aria-labelledby="evidence-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Tab'){e.preventDefault();e.currentTarget.querySelector<HTMLButtonElement>('button')?.focus();}}}><div className="modal-heading"><h2 id="evidence-title">{evidence.label} · page text</h2><button className="icon-button" onClick={closeEvidence} aria-label="Close" autoFocus><X size={20}/></button></div><div className="evidence-value">{evidence.cell.value}</div><blockquote>{evidence.cell.quote}</blockquote><p>Page content collected in this run</p></section></div>}
 </div>;
}
function ArrowDownIcon(){return <ArrowRight size={13} style={{transform:'rotate(45deg)'}}/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
